[versions]
agp = "8.4.2"
kotlin = "1.9.24"
compileSdk = "34"
minSdk = "24"
targetSdk = "34"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
